const services = [
  {
    title: 'Custom Software Development',
    description: 'We architect and build bespoke software solutions tailored to your business needs — from MVPs to enterprise-grade platforms.',
    icon: 'FaLaptopCode',
    features: ['Requirements Analysis', 'System Architecture', 'Agile Development', 'QA & Testing', 'Post-Launch Support'],
    color: '#0073E6',
    order: 1,
  },
  {
    title: 'SaaS Product Development',
    description: 'End-to-end SaaS platform development with multi-tenancy, subscription billing, analytics, and scalable cloud infrastructure.',
    icon: 'FaCloudUploadAlt',
    features: ['Multi-Tenant Architecture', 'Stripe Billing', 'Usage Analytics', 'Role-Based Access', 'Auto-Scaling'],
    color: '#00C6FF',
    order: 2,
  },
  {
    title: 'Enterprise Web Applications',
    description: 'Robust, secure, and high-performance web applications for large organizations with complex workflows and integrations.',
    icon: 'FaBuilding',
    features: ['ERP & CRM Systems', 'Workflow Automation', 'SSO Integration', 'Audit Logging', 'High Availability'],
    color: '#6C63FF',
    order: 3,
  },
  {
    title: 'Mobile App Development',
    description: 'Cross-platform and native mobile applications for iOS and Android with seamless UX and backend integration.',
    icon: 'FaMobileAlt',
    features: ['React Native', 'Flutter', 'Offline Mode', 'Push Notifications', 'App Store Deployment'],
    color: '#00D4AA',
    order: 4,
  },
  {
    title: 'API & Microservices',
    description: 'Scalable microservices architecture and robust RESTful/GraphQL APIs with security, documentation, and DevOps pipelines.',
    icon: 'FaProjectDiagram',
    features: ['REST & GraphQL', 'Microservices', 'API Gateway', 'OAuth 2.0 / JWT', 'Swagger Docs'],
    color: '#FF6B35',
    order: 5,
  },
  {
    title: 'UI/UX Design & Prototyping',
    description: 'Pixel-perfect, user-centered design that converts visitors into customers — from wireframes to fully interactive prototypes.',
    icon: 'FaPencilRuler',
    features: ['User Research', 'Figma Prototypes', 'Design Systems', 'Responsive Design', 'Usability Testing'],
    color: '#E91E8C',
    order: 6,
  },
  {
    title: 'Cloud & DevOps',
    description: 'Cloud migration, infrastructure as code, CI/CD pipelines, container orchestration, and 24/7 monitoring.',
    icon: 'FaServer',
    features: ['AWS / GCP / Azure', 'Docker & Kubernetes', 'CI/CD Pipelines', 'Terraform IaC', '99.9% Uptime SLA'],
    color: '#FF9500',
    order: 7,
  },
  {
    title: 'AI & Machine Learning',
    description: 'Intelligent software solutions powered by AI — chatbots, recommendation engines, predictive analytics, and NLP.',
    icon: 'FaBrain',
    features: ['NLP & Chatbots', 'Recommendation Systems', 'Predictive Analytics', 'Computer Vision', 'LLM Integration'],
    color: '#9C27B0',
    order: 8,
  },
];

const projects = [
  {
    title: 'NexaERP – Enterprise Resource Planning',
    description: 'A comprehensive ERP system for a 500+ employee manufacturing company covering HR, inventory, accounting, procurement, and real-time reporting with role-based dashboards.',
    category: 'fullstack',
    tech: ['React', 'Node.js', 'MongoDB', 'Redux Toolkit', 'Tailwind CSS', 'Docker', 'AWS'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    order: 1,
  },
  {
    title: 'CloudDesk – B2B SaaS Helpdesk',
    description: 'Multi-tenant SaaS helpdesk platform with AI-powered ticket routing, SLA management, customer portal, live chat, and in-depth analytics dashboards.',
    category: 'fullstack',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Socket.io', 'Stripe', 'Kubernetes'],
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    order: 2,
  },
  {
    title: 'MediCore – Hospital Management System',
    description: 'End-to-end hospital software covering patient records (EMR), appointment scheduling, pharmacy, billing, lab results, and telemedicine features.',
    category: 'fullstack',
    tech: ['React', 'Express', 'MongoDB', 'JWT', 'Chart.js', 'HIPAA Compliant'],
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    order: 3,
  },
  {
    title: 'EduHub – Learning Management System',
    description: 'Feature-rich LMS with video course hosting, live classes, quizzes, certificates, progress tracking, and instructor revenue sharing.',
    category: 'fullstack',
    tech: ['React', 'Node.js', 'MongoDB', 'Cloudinary', 'Stripe', 'Redis'],
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
    order: 4,
  },
  {
    title: 'FinTrack – Financial Analytics Platform',
    description: 'Real-time financial analytics SaaS for SMBs with automated bookkeeping, cash flow forecasting, tax reports, and bank reconciliation.',
    category: 'web',
    tech: ['React', 'D3.js', 'Node.js', 'MongoDB', 'Plaid API', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
    order: 5,
  },
  {
    title: 'LogiTrack – Supply Chain Software',
    description: 'IoT-integrated supply chain visibility platform with real-time GPS tracking, predictive delivery ETAs, and automated vendor management.',
    category: 'fullstack',
    tech: ['React', 'Node.js', 'MongoDB', 'Google Maps API', 'MQTT', 'Docker'],
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    order: 6,
  },
];

const testimonials = [
  {
    name: 'Arjun Mehta',
    role: 'CEO & Founder',
    company: 'NexaCore Technologies, India',
    text: 'CraftBit Tech BD transformed our entire operations with a custom ERP. Their software architecture is world-class. Delivered on time, within budget, and the codebase is clean and maintainable. Absolutely phenomenal team!',
    avatar: 'https://i.pravatar.cc/100?img=3',
    rating: 5,
    country: 'India',
    order: 1,
  },
  {
    name: 'Sarah Mitchell',
    role: 'CTO',
    company: 'Axiom Digital Solutions, UK',
    text: 'We outsourced our entire SaaS product to CraftBit and they exceeded every expectation. The Redux state management is flawless, the UI is pixel-perfect, and they even suggested improvements we hadn\'t thought of.',
    avatar: 'https://i.pravatar.cc/100?img=5',
    rating: 5,
    country: 'UK',
    order: 2,
  },
  {
    name: 'Dr. Hassan Al-Farsi',
    role: 'Director of IT',
    company: 'Gulf Medical Group, UAE',
    text: 'Our hospital needed a HIPAA-compliant system urgently. CraftBit delivered MediCore in 3 months — a full EMR and billing system. The quality and professionalism are unmatched in the region.',
    avatar: 'https://i.pravatar.cc/100?img=12',
    rating: 5,
    country: 'UAE',
    order: 3,
  },
  {
    name: 'Priya Sharma',
    role: 'Product Manager',
    company: 'SkillBridge EdTech, Singapore',
    text: 'The LMS they built for us handles 50,000+ students without breaking a sweat. The Cloudinary integration, live class feature, and certificate generation work flawlessly. Highly recommended!',
    avatar: 'https://i.pravatar.cc/100?img=9',
    rating: 5,
    country: 'Singapore',
    order: 4,
  },
  {
    name: 'James O\'Brien',
    role: 'VP of Engineering',
    company: 'LogiPro Ventures, Australia',
    text: 'CraftBit built our IoT supply chain platform with real-time GPS and MQTT integration. Their DevOps setup with Docker and Kubernetes keeps us at 99.98% uptime. Best investment we\'ve made.',
    avatar: 'https://i.pravatar.cc/100?img=7',
    rating: 5,
    country: 'Australia',
    order: 5,
  },
];

const team = [
  {
    name: 'Md. Anik Rahman',
    role: 'CEO & Lead Software Architect',
    bio: 'Software architect with 6+ years of experience delivering enterprise-grade solutions for clients across 15+ countries.',
    photo: 'https://i.pravatar.cc/200?img=11',
    skills: ['System Architecture', 'Node.js', 'React', 'AWS', 'MongoDB'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 1,
  },
  {
    name: 'Fatema Khatun',
    role: 'Head of Design',
    bio: 'Award-winning UI/UX designer specializing in enterprise software interfaces and design systems used by thousands of users.',
    photo: 'https://i.pravatar.cc/200?img=47',
    skills: ['Figma', 'Design Systems', 'Tailwind CSS', 'User Research', 'Prototyping'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 2,
  },
  {
    name: 'Shakib Hossain',
    role: 'Senior Backend Engineer',
    bio: 'Microservices specialist with deep expertise in high-performance APIs, DevOps, and cloud infrastructure at scale.',
    photo: 'https://i.pravatar.cc/200?img=15',
    skills: ['Node.js', 'Docker', 'Kubernetes', 'PostgreSQL', 'Redis', 'AWS'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 3,
  },
  {
    name: 'Nusrat Jahan',
    role: 'Senior Frontend Engineer',
    bio: 'React and Redux expert building accessible, performant UIs for complex enterprise dashboards and SaaS products.',
    photo: 'https://i.pravatar.cc/200?img=48',
    skills: ['React.js', 'Redux Toolkit', 'TypeScript', 'Tailwind CSS', 'Testing Library'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 4,
  },
  {
    name: 'Rafiqul Islam',
    role: 'Mobile App Developer',
    bio: 'Cross-platform mobile developer with published apps on both App Store and Play Store with combined 100K+ downloads.',
    photo: 'https://i.pravatar.cc/200?img=33',
    skills: ['React Native', 'Flutter', 'Firebase', 'App Store', 'Play Store'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 5,
  },
  {
    name: 'Tanvir Ahmed',
    role: 'DevOps & Cloud Engineer',
    bio: 'AWS-certified engineer managing CI/CD pipelines, container orchestration, and infrastructure for 20+ production applications.',
    photo: 'https://i.pravatar.cc/200?img=21',
    skills: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'GitHub Actions'],
    social: { linkedin: '#', github: '#', twitter: '#' },
    order: 6,
  },
];

module.exports = { services, projects, testimonials, team };
